# Generated by Django 4.2.4 on 2023-08-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
