# Generated by Django 4.2.4 on 2023-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_post_thumbnail_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
