# Generated by Django 4.2.4 on 2023-08-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_post_thumb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Free_Tutorials',
        ),
    ]
