# Generated by Django 4.2.4 on 2023-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_post_free_tutorials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_tutorials',
            name='body_tag',
        ),
        migrations.AddField(
            model_name='free_tutorials',
            name='body',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
