# Generated by Django 4.2.4 on 2023-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_free_tutorials_body_tag_free_tutorials_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_tutorials',
            name='body',
            field=models.CharField(default='\n\tTo Contact Us.... - 076 228 9809\n\tWe Are Available in Whatsapp and Telegram...\n\t', max_length=100, null=True),
        ),
    ]
