# Generated by Django 4.2.4 on 2023-08-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_free_tutorials_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
